### ISSUE TITLE
cb(null, info) TypeError: undefined is not a function

### ISSUE THREAD

**Issue by AlexanderMatveev** [nshkuro/node-fb2#1]
cb(null, info);
^
TypeError: undefined is not a function

at /home/alex/data/www/libsta.net/node/libsta_node/node_modules/node-fb2/lib/parser.js:44:9

**Comment by nshkuro** [comment]
Fixed readme. Try to use in async style.

``` js
fb2.parse('/path/to/file.fb2', function(error, bookMeta) {
    // Do anything
});
```

Thanks for your report.
